-- File generated by the BNF Converter (bnfc 2.9.6.2).

-- | Program to test parser.
module Main where

import Control.Monad (when)
import Syntax.Abs (Program)
import Syntax.Lex (Token, mkPosToken)
import Syntax.Par (myLexer, pProgram)
import Syntax.Print (Print, printTree)
import Syntax.TypeChecker (typeCheck)
import System.Environment (getArgs)
import System.Exit (exitFailure, exitSuccess)
import System.IO (hPrint, hPutStrLn, print, stderr)
import Prelude
  ( Either (..),
    FilePath,
    IO,
    Int,
    Show,
    String,
    concat,
    getContents,
    mapM_,
    putStrLn,
    readFile,
    show,
    unlines,
    ($),
    (++),
    (.),
    (>),
    (>>),
    (>>=),
  )

type Err = Either String

type ParseFun a = [Token] -> Err a

type Verbosity = Int

putStrV :: Verbosity -> String -> IO ()
putStrV v s = when (v > 1) $ putStrLn s

runFile :: Verbosity -> ParseFun Program -> FilePath -> IO ()
runFile v p f = putStrLn f >> readFile f >>= run v p

run :: Verbosity -> ParseFun Program -> String -> IO ()
run v p s =
  case p ts of
    Left err -> do
      hPutStrLn stderr "Parse Failed...\n"
      exitFailure
    Right tree ->
      case typeCheck tree of
        (Right ()) -> exitSuccess
        (Left err) -> do
          hPrint stderr err
          exitFailure
  where
    ts = myLexer s

usage :: IO ()
usage = do
  putStrLn $
    unlines
      [ "usage: Call with one of the following argument combinations:",
        "  --help          Display this help message.",
        "  (no arguments)  Parse stdin verbosely and type-check it",
        "  (files)         Parse content of files verbosely and type-check it."
      ]

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> usage
    [] -> getContents >>= run 2 pProgram
    fs -> mapM_ (runFile 2 pProgram) fs
