-- File generated by the BNF Converter (bnfc 2.9.6.2).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transStellaIdent :: Syntax.Abs.StellaIdent -> Result
transStellaIdent x = case x of
  Syntax.Abs.StellaIdent string -> failure x

transExtensionName :: Syntax.Abs.ExtensionName -> Result
transExtensionName x = case x of
  Syntax.Abs.ExtensionName string -> failure x

transMemoryAddress :: Syntax.Abs.MemoryAddress -> Result
transMemoryAddress x = case x of
  Syntax.Abs.MemoryAddress string -> failure x

transProgram :: Syntax.Abs.Program -> Result
transProgram x = case x of
  Syntax.Abs.AProgram languagedecl extensions decls -> failure x

transLanguageDecl :: Syntax.Abs.LanguageDecl -> Result
transLanguageDecl x = case x of
  Syntax.Abs.LanguageCore -> failure x

transExtension :: Syntax.Abs.Extension -> Result
transExtension x = case x of
  Syntax.Abs.AnExtension extensionnames -> failure x

transDecl :: Syntax.Abs.Decl -> Result
transDecl x = case x of
  Syntax.Abs.DeclFun annotations stellaident paramdecls returntype throwtype decls expr -> failure x
  Syntax.Abs.DeclFunGeneric annotations stellaident stellaidents paramdecls returntype throwtype decls expr -> failure x
  Syntax.Abs.DeclTypeAlias stellaident type_ -> failure x
  Syntax.Abs.DeclExceptionType type_ -> failure x
  Syntax.Abs.DeclExceptionVariant stellaident type_ -> failure x

transLocalDecl :: Syntax.Abs.LocalDecl -> Result
transLocalDecl x = case x of
  Syntax.Abs.ALocalDecl decl -> failure x

transAnnotation :: Syntax.Abs.Annotation -> Result
transAnnotation x = case x of
  Syntax.Abs.InlineAnnotation -> failure x

transParamDecl :: Syntax.Abs.ParamDecl -> Result
transParamDecl x = case x of
  Syntax.Abs.AParamDecl stellaident type_ -> failure x

transReturnType :: Syntax.Abs.ReturnType -> Result
transReturnType x = case x of
  Syntax.Abs.NoReturnType -> failure x
  Syntax.Abs.SomeReturnType type_ -> failure x

transThrowType :: Syntax.Abs.ThrowType -> Result
transThrowType x = case x of
  Syntax.Abs.NoThrowType -> failure x
  Syntax.Abs.SomeThrowType types -> failure x

transType :: Syntax.Abs.Type -> Result
transType x = case x of
  Syntax.Abs.TypeAuto -> failure x
  Syntax.Abs.TypeFun types type_ -> failure x
  Syntax.Abs.TypeForAll stellaidents type_ -> failure x
  Syntax.Abs.TypeRec stellaident type_ -> failure x
  Syntax.Abs.TypeSum type_1 type_2 -> failure x
  Syntax.Abs.TypeTuple types -> failure x
  Syntax.Abs.TypeRecord recordfieldtypes -> failure x
  Syntax.Abs.TypeVariant variantfieldtypes -> failure x
  Syntax.Abs.TypeList type_ -> failure x
  Syntax.Abs.TypeBool -> failure x
  Syntax.Abs.TypeNat -> failure x
  Syntax.Abs.TypeUnit -> failure x
  Syntax.Abs.TypeTop -> failure x
  Syntax.Abs.TypeBottom -> failure x
  Syntax.Abs.TypeRef type_ -> failure x
  Syntax.Abs.TypeVar stellaident -> failure x

transMatchCase :: Syntax.Abs.MatchCase -> Result
transMatchCase x = case x of
  Syntax.Abs.AMatchCase pattern_ expr -> failure x

transOptionalTyping :: Syntax.Abs.OptionalTyping -> Result
transOptionalTyping x = case x of
  Syntax.Abs.NoTyping -> failure x
  Syntax.Abs.SomeTyping type_ -> failure x

transPatternData :: Syntax.Abs.PatternData -> Result
transPatternData x = case x of
  Syntax.Abs.NoPatternData -> failure x
  Syntax.Abs.SomePatternData pattern_ -> failure x

transExprData :: Syntax.Abs.ExprData -> Result
transExprData x = case x of
  Syntax.Abs.NoExprData -> failure x
  Syntax.Abs.SomeExprData expr -> failure x

transPattern :: Syntax.Abs.Pattern -> Result
transPattern x = case x of
  Syntax.Abs.PatternCastAs pattern_ type_ -> failure x
  Syntax.Abs.PatternAsc pattern_ type_ -> failure x
  Syntax.Abs.PatternVariant stellaident patterndata -> failure x
  Syntax.Abs.PatternInl pattern_ -> failure x
  Syntax.Abs.PatternInr pattern_ -> failure x
  Syntax.Abs.PatternTuple patterns -> failure x
  Syntax.Abs.PatternRecord labelledpatterns -> failure x
  Syntax.Abs.PatternList patterns -> failure x
  Syntax.Abs.PatternCons pattern_1 pattern_2 -> failure x
  Syntax.Abs.PatternFalse -> failure x
  Syntax.Abs.PatternTrue -> failure x
  Syntax.Abs.PatternUnit -> failure x
  Syntax.Abs.PatternInt integer -> failure x
  Syntax.Abs.PatternSucc pattern_ -> failure x
  Syntax.Abs.PatternVar stellaident -> failure x

transLabelledPattern :: Syntax.Abs.LabelledPattern -> Result
transLabelledPattern x = case x of
  Syntax.Abs.ALabelledPattern stellaident pattern_ -> failure x

transBinding :: Syntax.Abs.Binding -> Result
transBinding x = case x of
  Syntax.Abs.ABinding stellaident expr -> failure x

transExpr :: Syntax.Abs.Expr -> Result
transExpr x = case x of
  Syntax.Abs.Sequence expr1 expr2 -> failure x
  Syntax.Abs.Assign expr1 expr2 -> failure x
  Syntax.Abs.If expr1 expr2 expr3 -> failure x
  Syntax.Abs.Let patternbindings expr -> failure x
  Syntax.Abs.LetRec patternbindings expr -> failure x
  Syntax.Abs.TypeAbstraction stellaidents expr -> failure x
  Syntax.Abs.LessThan expr1 expr2 -> failure x
  Syntax.Abs.LessThanOrEqual expr1 expr2 -> failure x
  Syntax.Abs.GreaterThan expr1 expr2 -> failure x
  Syntax.Abs.GreaterThanOrEqual expr1 expr2 -> failure x
  Syntax.Abs.Equal expr1 expr2 -> failure x
  Syntax.Abs.NotEqual expr1 expr2 -> failure x
  Syntax.Abs.TypeAsc expr type_ -> failure x
  Syntax.Abs.TypeCast expr type_ -> failure x
  Syntax.Abs.Abstraction paramdecls expr -> failure x
  Syntax.Abs.Variant stellaident exprdata -> failure x
  Syntax.Abs.Match expr matchcases -> failure x
  Syntax.Abs.List exprs -> failure x
  Syntax.Abs.Add expr1 expr2 -> failure x
  Syntax.Abs.Subtract expr1 expr2 -> failure x
  Syntax.Abs.LogicOr expr1 expr2 -> failure x
  Syntax.Abs.Multiply expr1 expr2 -> failure x
  Syntax.Abs.Divide expr1 expr2 -> failure x
  Syntax.Abs.LogicAnd expr1 expr2 -> failure x
  Syntax.Abs.Ref expr -> failure x
  Syntax.Abs.Deref expr -> failure x
  Syntax.Abs.Application expr exprs -> failure x
  Syntax.Abs.TypeApplication expr types -> failure x
  Syntax.Abs.DotRecord expr stellaident -> failure x
  Syntax.Abs.DotTuple expr integer -> failure x
  Syntax.Abs.Tuple exprs -> failure x
  Syntax.Abs.Record bindings -> failure x
  Syntax.Abs.ConsList expr1 expr2 -> failure x
  Syntax.Abs.Head expr -> failure x
  Syntax.Abs.IsEmpty expr -> failure x
  Syntax.Abs.Tail expr -> failure x
  Syntax.Abs.Panic -> failure x
  Syntax.Abs.Throw expr -> failure x
  Syntax.Abs.TryCatch expr1 pattern_ expr2 -> failure x
  Syntax.Abs.TryWith expr1 expr2 -> failure x
  Syntax.Abs.TryCastAs expr1 type_ pattern_ expr2 expr3 -> failure x
  Syntax.Abs.Inl expr -> failure x
  Syntax.Abs.Inr expr -> failure x
  Syntax.Abs.Succ expr -> failure x
  Syntax.Abs.LogicNot expr -> failure x
  Syntax.Abs.Pred expr -> failure x
  Syntax.Abs.IsZero expr -> failure x
  Syntax.Abs.Fix expr -> failure x
  Syntax.Abs.NatRec expr1 expr2 expr3 -> failure x
  Syntax.Abs.Fold type_ expr -> failure x
  Syntax.Abs.Unfold type_ expr -> failure x
  Syntax.Abs.ConstTrue -> failure x
  Syntax.Abs.ConstFalse -> failure x
  Syntax.Abs.ConstUnit -> failure x
  Syntax.Abs.ConstInt integer -> failure x
  Syntax.Abs.ConstMemory memoryaddress -> failure x
  Syntax.Abs.Var stellaident -> failure x

transPatternBinding :: Syntax.Abs.PatternBinding -> Result
transPatternBinding x = case x of
  Syntax.Abs.APatternBinding pattern_ expr -> failure x

transVariantFieldType :: Syntax.Abs.VariantFieldType -> Result
transVariantFieldType x = case x of
  Syntax.Abs.AVariantFieldType stellaident optionaltyping -> failure x

transRecordFieldType :: Syntax.Abs.RecordFieldType -> Result
transRecordFieldType x = case x of
  Syntax.Abs.ARecordFieldType stellaident type_ -> failure x

transTyping :: Syntax.Abs.Typing -> Result
transTyping x = case x of
  Syntax.Abs.ATyping expr type_ -> failure x
